### ISSUE TITLE
Suggestion: Medical Items

### ISSUE THREAD

**Issue by Ashouwii** [BSuzinator/GHG_Framework#2]
Suggestion can we remake medic loadout so they have only elastic and packing? 
Also, can everyone else have more tourniquets like 3 or more?
OHH and more smokes for everyone aka more white smokes to cover us.

**Comment by BSuzinator** [comment]
Proposed Change - Lose 16 total, or up to 40 ea. Elastic/Packing
      ["ACE_elasticBandage",32],
      ["ACE_packingBandage",32],
      ["ACE_bloodIV_250",8],
      ["ACE_bloodIV_500",4],
      ["ACE_bloodIV",4],
      ["ACE_surgicalKit",1],
      ["ACE_personalAidKit",2],
      ["ACE_splint",10],
      ["ACE_morphine",12],
      ["ACE_epinephrine",12],
      ["ACE_EarPlugs",1]

Up each unit's tourniquets to 2 from 1

**Comment by BSuzinator** [comment]
Changes will be in effect next framework update
