### ISSUE TITLE
Gimme Chemlight Shields in the fucking Chemlight crates you're making Brandon - Firestorm4594

### ISSUE THREAD

**Issue by GHG-Team** [BSuzinator/GHG_Framework#34]
Exactly what the title says
-Submitted by Firestorm4594

**Comment by BSuzinator** [comment]
Added with inventory:
Chemlight_blue", 10
ACE_Chemlight_HiBlue", 10
Chemlight_green", 10
ACE_Chemlight_HiGreen", 10
Chemlight_red", 10
ACE_Chemlight_HiRed", 10
Chemlight_yellow", 10
ACE_Chemlight_HiYellow", 10
ACE_Chemlight_White", 10
ACE_Chemlight_HiWhite", 10
ACE_Chemlight_Orange", 10
ACE_Chemlight_UltraHiOrange", 10
ACE_Chemlight_IR", 10
ACE_Chemlight_Shield", 20
