### ISSUE TITLE
Create a "Night OPs" Crate - Firestorm4594

### ISSUE THREAD

**Issue by GHG-Team** [BSuzinator/GHG_Framework#35]
Add Suppressors, water bottles (for the heating suppressors) and things like IR Strobes into a crate, so if the OP has a possibility to run into the night and starts in daytime, we can spawn this in to crack open when night comes... Heavy down comes to mind
-Submitted by Firestorm4594

**Comment by BSuzinator** [comment]
Will not add, if suppressors are intended for a mission the appropriate factions should be used by the creator.
