### ISSUE TITLE
SOG Prarie Fire Maps do not allow use of map tools - Firestorm4594

### ISSUE THREAD

**Issue by GHG-Team** [BSuzinator/GHG_Framework#38]
replacing the maps only changes the icon to be more period appropriate and isn't a mechanical bug, when possible we should use base game maps it seems in loadouts
-Submitted by Firestorm4594

**Comment by BSuzinator** [comment]
Could potentially change 'nam loadouts to use base maps
[https://github.com/acemod/ACE3/blob/e0df864a5d0778174491bd135947f474c93e9330/addons/maptools/functions/fnc_canUseMapTools.sqf#L20](https://github.com/acemod/ACE3/blob/e0df864a5d0778174491bd135947f474c93e9330/addons/maptools/functions/fnc_canUseMapTools.sqf#L20)

**Comment by BSuzinator** [comment]
Trying a really longshot fix, not sure if it'll work but we'll try it

**Comment by BSuzinator** [comment]
didn't work
